# site properties and page defaults
title: P-Badger Lab
subtitle: Psychiatric Behavioral Aging Dementia Genomics Research
description: We utilize multivariate genomic methods to better understand the underlying factors that impact psychiatric and cognitive traits.
header: images/background.jpg
footer: images/background.jpg
proofer: false

# site social media and other links
links:
  email: "mailto:andrew.grotzinger@colorado.edu"
  orcid: 0000-0001-7852-9244
  google-scholar: m6VyKjkAAAAJ&hl
  github: agrotzin
  bluesky: andrewgrotzinger

### jekyll settings

# front matter defaults
defaults:
  # all markdown files
  - scope:
      path: ""
    values:
      layout: default
  # markdown files in /_members
  - scope:
      type: "members"
    values:
      layout: member
  # markdown files in /_posts
  - scope:
      type: "posts"
    values:
      layout: post

collections:
  # generate page for each member
  members:
    output: true
  # generate page for each post
  posts:
    output: true

# jekyll plugins
plugins:
  - jekyll-spaceship
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-last-modified-at

# code block syntax highlighting
highlighter: rouge

# jekyll theme
theme: null

# sass settings
sass:
  sass_dir: _styles

# force jekyll to include certain files/folders
include:
  - _styles
  - _scripts

# force jekyll to exclude certain files/folders
exclude:
  - README.md
  - LICENSE.md
  - CITATION.cff
